export { default as treble } from './Resources.Images.treble.png';
export { default as bass } from './Resources.Images.bass.png';
export { default as two } from './Resources.Images.two.png';
export { default as three } from './Resources.Images.three.png';
export { default as four } from './Resources.Images.four.png';
export { default as six } from './Resources.Images.six.png';
export { default as eight } from './Resources.Images.eight.png';
export { default as nine } from './Resources.Images.nine.png';
export { default as twelve } from './Resources.Images.twelve.png';
