//piano
export const LOAD_FILE_SUCCESS = 'LOAD_FILE_SUCCESS';
export const LOAD_FILE_DATA_SUCCESS = 'LOAD_FILE_DATA_SUCCESS';
export const TRACK_DISPLAY_UPDATE = 'TRACK_DISPLAY_UPDATE';
export const TRACK_PLAY_UPDATE = 'TRACK_PLAY_UPDATE';

//player
export const PLAY = 'PLAY';
export const PAUSE = 'PAUSE';
export const SET_TEMPO = 'SET_TEMPO';
export const INIT_PLAYER_TRACK_SETTINGS = 'INIT_PLAYER_TRACK_SETTINGS';

//sheetMusicOutput
export const SHEET_MUSIC_SELECTION_CHANGED = 'SHEET_MUSIC_SELECTION_CHANGED';
export const SHEET_MUSIC_AUTOSCROLL_CHANGED = 'SHEET_MUSIC_AUTOSCROLL_CHANGED';

//midiKeyboardInput
export const WAIT_FOR_INPUT_CHANGED = 'WAIT_FOR_INPUT_CHANGED';
export const INPUT_STAFFS_CHANGED = 'INPUT_STAFFS_CHANGED';
export const SET_MIDI_KEYBOARD_PORT_ID = 'SET_MIDI_KEYBOARD_PORT_ID';

//ledStripOutput
export const SET_LED_STRIP_PORT_ID = 'SET_LED_STRIP_PORT_ID';