//piano
export const LOAD_FILE_SUCCESS = 'LOAD_FILE_SUCCESS';
export const LOAD_FILE_DATA_SUCCESS = 'LOAD_FILE_DATA_SUCCESS';
export const TRACK_DISPLAY_UPDATE = 'TRACK_DISPLAY_UPDATE';
export const TRACK_PLAY_UPDATE = 'TRACK_PLAY_UPDATE';

//player
export const PLAY = 'PLAY';
export const PAUSE = 'PAUSE';
export const SET_TEMPO = 'SET_TEMPO';

//sheetMusicOutput
export const SHEET_MUSIC_SELECTION_CHANGED = 'SHEET_MUSIC_SELECTION_CHANGED';
export const SHEET_MUSIC_AUTOSCROLL_CHANGED = 'SHEET_MUSIC_AUTOSCROLL_CHANGED';